embed_assets: on
compress_assets: on
javascript_compressor: closure

javascripts:
  common:
    - public/javascripts/jquery.js
    - public/javascripts/jquery-ui.min.js
    - public/javascripts/jquery.jeditable.js
    - public/javascripts/jquery.jgrowl.js
    - public/javascripts/hatrack.js
stylesheets:
  blueprint:
    - public/stylesheets/compiled/screen.css
  common:
    - public/stylesheets/jquery-ui.css
    - public/stylesheets/formtastic.css
    - public/stylesheets/formtastic_changes.css
    - public/stylesheets/jquery.jgrowl.css
  hatrack:
    - public/stylesheets/compiled/hatrack.css
  homepage: 
    - public/stylesheets/compiled/homepage.css
