embed_assets: on
compress_assets: on
javascript_compressor: closure

javascripts:
  common:
    - public/javascripts/jquery.js
    - public/javascripts/jquery.jeditable.js
    - public/javascripts/hatrack.js
stylesheets:
  blueprint:
    - public/stylesheets/compiled/screen.css
    - public/stylesheets/compiled/print.css
  common:
    - public/stylesheets/compiled/hatrack.css
