development:
    host: localhost
    port: 27017
    database: hatrack-development
test:
    host: localhost
    port: 27017
    database: hatrack-test
staging:
    host: localhost
    port: 27017
    database: hatrack-staging
production:
    host: swan.mongohq.com
    port: 27019
    database: hats
    username: theath
    password: omgmongo
